### PR TITLE
reduce the number of files in the npm package

### PR DESCRIPTION
**Pull request by silverwind**
Reduce the number of files in the npm package by using the files array whitelist. README.md and LICENCE are automatically included by npm:

https://docs.npmjs.com/files/package.json#files

### CODE REVIEW

**Comment by thejoshwolfe** [comment]
What's the point of .npmignore if you only list a single file in package.json?

**Comment by silverwind** [comment]
The point is that `files` is that it's a whitelist approach, while `.npmignore` is a blacklist. With the latter, it's easy to publish leftover files to npm, something which isn't possible with `files`. Also, in your case, the package just got lighter by not including useless dotfiles.

**Comment by thejoshwolfe** [comment]
oh! i just read the commit wrong. you did delete` .npmignore`. cool.

**Comment by silverwind** [comment]
Yeah, GitHub's new Diff UI doesn't really make it clear anymore when a files was deleted :(

**Pull request merged**
