### PR TITLE
Add new zip64 test, by checking in a zip64 file containing two 3-byte files

### PR DESCRIPTION
**Pull request by mwoc**
While I was working on a library using yauzl to unzip files, I ran into the 'how to assert that zip64 works' issue as well (as there was a bug in my RandomAccessReader that broke for zip64), and spent some time constructing a test file that is small enough to check in and work with, but is actually a zip64 file.

I figured you might be interested in using such a test file for the zip64 tests.

~~If you like the idea and are interested in making more tests for zip64 - I created it using https://github.com/archiverjs/node-archiver, by making the two 'isZip64' functions in its dependency https://github.com/archiverjs/node-compress-commons/blob/master/lib/archivers/zip/ (through https://github.com/archiverjs/node-zip-stream) always return true. I've sent a PR to them as well https://github.com/archiverjs/node-compress-commons/pull/20 for making that easier.~~

### CODE REVIEW

**Comment by mwoc** [comment]
Ah, just saw the forceZip64Format functionality in yazl.

**Comment by thejoshwolfe** [comment]
i think having some complete zip64 archives in the success/ directory is a good idea. however, i don't want to delete the existing zip64 test just yet. it does a lot more than test zip64 format, like doing nontrivial things with the RandomAccessReader api. It's also nice to actually test numbers greater than `2**32`, which is what all the complexity in that test accomplishing.

In short, I'm happy to merge your additions, but not the deletions.

**Comment by mwoc** [comment]
Ah alright, yes better to not decrease coverage. I've pushed a new commit which only adds the new file.

**Comment by thejoshwolfe** [comment]
Sorry I've been neglecting this PR. It looks like there's some good stuff in here.

I've been working on a utility that will examine all the details of a zipfile and show an annotated hex dump to help developers (mostly me) parse a zipfile binary manually. Check out `test/show_zip_structure.js` if you'd like to play around with it.

When I use the utility on your zipfile, I think it spots a mistake, although it's one that yauzl will ignore.

In your "ZIP64 End of Central Directory Record", the "size of zip64 end of central directory record" is 12 too big. Note this paragraph from the spec:

> 4.3.14.1 The value stored into the "size of zip64 end of central
> directory record" should be the size of the remaining
> record and should not include the leading 12 bytes.

Even so, the tests pass, and this is a great PR. Thanks!

I'm going to merge, and fix the "mistake" in another commit.

**Pull request merged**
