### PR TITLE
Optimize reading ZIP64 End of Central Directory Records to call `reader.read()` fewer times

### PR DESCRIPTION
**Pull request by overlookmotel**
This PR is a minor optimization for reading ZIP64 End of Central Directory Records.

With a ZIP64 file, often the initial call to `reader.read()` to get the End of Central Directory Record will also gather the data containing ZIP64 End of Central Directory Records too (if end comment section is shorter than the maximum).

Current behaviour: If the file is ZIP64, 2 further calls to `reader.read()` are made to read the Zip64 End of Central Directory Locator and ZIP64 End of Central Directory Record.

This PR adds a check for whether some of the ZIP64 CDL+CDR data has already been collected by the initial `reader.read()` call, and is already in memory. If so, it uses the buffered data and does not make further calls to `reader.read()`. Or, if only part of required data is buffered, it reads only the new data required. i.e. avoids calling `reader.read()` twice to read the same data.

This is a pretty minor optimization, and you may not consider it worth merging. I've done it as an exercise way to learn my way around the codebase as much as anything.

### CODE REVIEW

**Comment by overlookmotel** [comment]
A set of tests for the `readAndAssertNoEofWithCache` function are [here](https://github.com/overlookmotel/yauzl/blob/optimize-zip64-header-test/zip64optimize.test.js) (requires mocha and chai).

**Comment by thejoshwolfe** [comment]
I'd like to see performance measurements before merging this optimization. There's a chance that in the common case, this doesn't help, because FS IO is cached anyway. We can both speculate and theorize, but measurements would be ideal. And I'm not sure exactly how to collect measurements while being careful with things like FS IO cache.

**Comment by overlookmotel** [comment]
@thejoshwolfe Yes you're right this may be a complication too far for minimal/no performance gain in the common case.

Where this *would* be more useful is when the ZIP file is opened with `fromRandomAccessReader()` and every read call causes a network action e.g. Google API call to fetch a bit of the file from Google Drive. But in that case, there are likely many other optimizations which could be made e.g. fetching the whole of the central directory in one go, rather than in small chunks.

Perhaps this would be better implemented within the reader, dependent on the specific use case.

Feel free to close this PR if you like.

**Comment by thejoshwolfe** [comment]
> optimizations which could be made e.g. fetching the whole of the central directory in one go, rather than in small chunks.

Sure. If you intend to get a listing before extracting any elements, then this makes a lot of sense. You'd have to kinda guess how big it is though.

It probably depends on how the underlying fs works too, like if you can fetch a minimum of 8MB at a time, then that will inform the optimizations you make. Unfortunately, the zipfile format was designed for random access writing and reading on floppy disks (and even then, designed badly), so there's really no obvious generic optimizations we can do.

**Pull request closed without merging**
