### PR TITLE
Get the correct fileName from extra filed when decodeStrings is false

### PR DESCRIPTION
**Pull request by fpsqdb**
This commit [add option decodeStrings](https://github.com/thejoshwolfe/yauzl/commit/cc7455ac789ba84973184e5ebde0581cdc4c3b39) adds support return fileName or comment as buffer and fixes issue [#42](https://github.com/thejoshwolfe/yauzl/issues/42), but the fileName is not a buffer when `decodeStrings` is `false`.
This PR makes fileName is a buffer when `decodeStrings` is `false`.

### CODE REVIEW

**Comment by thejoshwolfe** [comment]
Sorry for the delayed response. I'm not sure I understand the purpose or intended effect of this PR. Are you trying to bypass the security validation but still support reading the Info-ZIP Unicode Path Extra Field? If that's the case, what part of the validation is causing issues for you?

**Comment by fpsqdb** [comment]
@thejoshwolfe Sorry, the commit link and related issue is wrrong, i have modified my comment.

**Comment by thejoshwolfe** [comment]
Why do you want an undecoded buffer for the file name?

**Comment by fpsqdb** [comment]
Set `decodeStrings` to false to decode the buffer by myself.
And the code implementation does not match the document description.
https://github.com/thejoshwolfe/yauzl#filename
> If decodeStrings is false (see open()), this field is the undecoded Buffer instead of a decoded String.

**Comment by thejoshwolfe** [comment]
> And the code implementation does not match the document description.

What's the discrepancy that you're seeing? If you're talking about how the undecoded `Buffer` is always the basic name and never the one from the Info-ZIP Unicode Path Extra Field, that's mentioned in the very next sentence in the docs. Maybe that could be communicated more clearly.

**Comment by fpsqdb** [comment]
The latest version has fixed this problem

**Pull request closed without merging**
